name: Test
on:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Fetch Project
      uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Set up System
      run: |
        sudo apt install libsqlite3-dev
    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Set up Nodejs
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: Cache Bundle
      uses: actions/cache@v1
      with:
        path: bundle
        key: ${{ runner.OS }}-bundle-${{ hashFiles('Gemfile.lock') }}
    - name: Cache Node Modules
      uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ runner.OS }}-yarn-${{ hashFiles('yarn.lock') }}
    - name: Install Dependencies
      run: |
        gem install bundler
        bundle install --path=bundle --jobs=4 --retry=3
        bin/yarn install --check-files
    - name: Prepare DB
      run: |
        bin/rails db:drop
        bin/rails db:setup
    - name: Run Test
      run: |
        bin/rails test -v -b
